#!/bin/sh

##
# Duke JAMF Package Workflow Utility
# https://github.com/duke-jamf/scripts
#
# Runs the test suite for all scripts.
##

TESTS=`dirname "$0"`
SCRIPTS="$TESTS/../src"

tear_down()
{
	killall "Seashore" > /dev/null 2>&1
	killall "Cyberduck" > /dev/null 2>&1
	rm -rf "$TESTS/witch"
	rm -rf "$TESTS/cyberduck/*.pkg"
	rm -f "$TESTS/cyberduck/.manifest"
}

# Require sudo immediately
echo "Gathering permission..."
sudo echo "	PASS!"

# Start with a clean slate
tear_down

echo "************************************"
echo "* SOURCE (CASK)                    *"
echo "************************************"

"$SCRIPTS/source-cask" "witch" "$TESTS"
RESULT=$?; if [ $RESULT -ne 0 ]; then tear_down; exit $RESULT; fi
if [ ! -f "$TESTS/witch/variables" ]; then echo "FAIL!"; tear_down; exit 1; fi
echo "	PASS!"

echo "************************************"
echo "* CHECK (CASK)                     *"
echo "************************************"

printf "Missing..."
RESULT=`"$SCRIPTS/check-cask" "$TESTS/cyberduck"`
if [ "$RESULT" != "missing" ]; then echo "	FAIL ($RESULT)"; tear_down; exit 1; fi
echo "	PASS!"

printf "Outdated..."
RESULT=`"$SCRIPTS/check-cask" "$TESTS/seashore"`
if [ "$RESULT" != "outdated" ]; then echo "	FAIL ($RESULT)"; tear_down; exit 1; fi
echo "	PASS!"

echo "************************************"
echo "* BUILD                            *"
echo "************************************"

echo "Standard build..."
"$SCRIPTS/build" "$TESTS/cyberduck"
RESULT=$?; if [ $RESULT -ne 0 ]; then tear_down; exit $RESULT; fi
echo "	PASS!"

echo "Build with arguments..."
"$SCRIPTS/build" "$TESTS/witch" "--analyze"
RESULT=$?; if [ $RESULT -ne 0 ]; then tear_down; exit $RESULT; fi

# Verify it created a PLIST instead of a package
printf "Verifying PLIST contents..."
for FILE in "$TESTS/witch"/*.pkg; do
	RESULT=`tail -n 1 "$FILE"`
	if [ "$RESULT" != "</plist>" ]; then echo "FAIL"; tear_down; exit 1; fi
done
echo "	PASS!"

echo "************************************"
echo "* CHECK (CASK)                     *"
echo "************************************"

printf "Current..."
RESULT=`"$SCRIPTS/check-cask" "$TESTS/cyberduck"`
if [ "$RESULT" != "current" ]; then echo "	FAIL ($RESULT)"; tear_down; exit 1; fi
echo "	PASS!"

echo "************************************"
echo "* VERIFY (BASIC)                   *"
echo "************************************"

sudo "$SCRIPTS/verify" "$TESTS/seashore"
RESULT=$?; if [ $RESULT -ne 0 ]; then tear_down; exit $RESULT; fi
echo "	PASS!"

echo "************************************"
echo "* VERIFY (CUSTOM)                  *"
echo "************************************"

sudo "$SCRIPTS/verify" "$TESTS/cyberduck"
RESULT=$?; if [ $RESULT -ne 0 ]; then tear_down; exit $RESULT; fi
echo "	PASS!"

echo "All tests passed!"

tear_down
exit 0
