#!/bin/sh

##
# Duke JAMF Package Workflow Utility
# https://github.com/duke-jamf/scripts
#
# Takes a package definition as input and builds a .pkg
##

if [ $# -lt 1 ]; then
    echo "Usage: build {path/to/definition} [pkgbuild_options]"
    exit 1
fi

SCRIPTS=`dirname "$0"`
DEFINITION="$1"
shift

# Load variables from the definition
. "$DEFINITION/variables"

echo "Building $PKGNAME via $PKGTYPE"

case $PKGTYPE in
	cask)
		"$SCRIPTS/build-cask" $PKGSLUG "$@"
		RESULT=$?
		if [ $RESULT -ne 0 ]; then
			echo "Unable to convert Cask to package: $PKGSLUG"
			exit $RESULT
		fi
		
		# Move the package and manifest into the definitions directory
		PKGNAME=`tail -n 1 ".manifest"`
		mv "$PKGNAME" "$DEFINITION/"
		mv ".manifest" "$DEFINITION/"

		break
		;;
esac

echo "Build of $PKGNAME succeeded!"

exit 0
